services:
  docs:
    image: cookie_cuts_local_docs
    container_name: cookie_cuts_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./cookie_cuts:/app/cookie_cuts:z
    ports:
      - '9000:9000'
    command: /start-docs
